### ISSUE TITLE
Raspberry 4B need I2C

### ISSUE THREAD

**Issue by rapemer** [Misiu/argon40#10]
When I turn on _argon40_, there was an error with missing I2C (`FileNotFoundError: [Errno 2] No such file or directory: '/dev/i2c-1'`) in my Raspberry 4B 8GB.. 

I was searching solution and problems fixed with advices at this links:
- https://www.home-assistant.io/hassio/enable_i2c/
- https://community.home-assistant.io/t/i2c-not-working-on-the-pi4/160489/7

It would be nice to add into documentation, can help others :-)

Secondary, I have suggestion to automatization of the Fan (in manual was mentioned temperatures and recommended power settings):

```yaml

- alias: "Fan speed 0% (<55°C)"
  trigger:
    platform: numeric_state
    entity_id: sensor.cpu_temp
    below: 55
  action:
    - service: argon40.set_fan_speed
      data:
        speed: 0

- alias: "Fan speed 10% (>55°C)"
  trigger:
    platform: numeric_state
    entity_id: sensor.cpu_temp
    above: 55
  action:
    - service: argon40.set_fan_speed
      data:
        speed: 10

- alias: "Fan speed 55% (>60°C)"
  trigger:
    platform: numeric_state
    entity_id: sensor.cpu_temp
    above: 60
  action:
    - service: argon40.set_fan_speed
      data:
        speed: 55

- alias: "Fan speed 100% (>65°C)"
  trigger:
    platform: numeric_state
    entity_id: sensor.cpu_temp
    above: 65
  action:
    - service: argon40.set_fan_speed
      data:
        speed: 100
```
