### ISSUE TITLE
[Bug] Fan Speed not changing

### ISSUE THREAD

**Issue by greghesp** [Misiu/argon40#17]
I've got an automation that turns the fan off if its below 50.  I can see that the automation has triggered and the CPU temperature is 30, however the fan speed does not change?

```
alias: '[Argon One] Turn Off Fan Below 50'
description: ''
trigger:
  - platform: numeric_state
    entity_id: sensor.cpu_temperature
    below: '50'
condition: []
action:
  - service: argon40.set_fan_speed
    data:
      speed: 0
mode: single
```
