### ISSUE TITLE
Sensor for fan speed

### ISSUE THREAD

**Issue by kirbo** [Misiu/argon40#24]
Is there a way for me to create a sensor to detect fan speeds?
I'm using the cpu temp sensor:
```yaml
- platform: command_line
  name: CPU Temp
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: "{{ value | multiply(0.001) | round(1) }}"
```
...and I tried to find something similar from the HASSOS command line, where I could see the speed of the fan, but I didn't get lucky.
