### ISSUE TITLE
readme cpu sensor code is wrong

### ISSUE THREAD

**Issue by heimwege** [Misiu/argon40#76]
Hey 👋🏻

current config for "Add CPU Temperature sensor" in the readme looks as follows:

```yaml
sensor:
  - platform: command_line
    name: CPU Temp
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: "{{ value | multiply(0.001) | round(1) }}"
```

but should be

```yaml
command_line:
  - sensor:
      name: CPU Temp
      unique_id: cpu_temp # unique identifier needed to be able to edit this sensor via GUI (change icon, etc.)
      command: "cat /sys/class/thermal/thermal_zone0/temp"
      unit_of_measurement: "°C"
      value_template: "{{ value | multiply(0.001) | round(1) }}"
```

see https://www.home-assistant.io/integrations/command_line/#cpu-temperature
